CREATE TABLE public.race_results (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  horse_id integer NOT NULL REFERENCES public.horses(id) ON DELETE CASCADE,
  race_id integer NOT NULL REFERENCES public.live_races(id) ON DELETE CASCADE,
  time_ms integer NOT NULL,
  raced_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.race_results TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.race_results TO authenticated;
GRANT ALL ON public.race_results TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;

ALTER TABLE public.race_results ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can view race results" ON public.race_results FOR SELECT USING (true);
CREATE POLICY "Anyone can insert race results" ON public.race_results FOR INSERT WITH CHECK (true);
CREATE POLICY "Anyone can update race results" ON public.race_results FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Anyone can delete race results" ON public.race_results FOR DELETE USING (true);

CREATE INDEX idx_race_results_horse ON public.race_results(horse_id);
CREATE INDEX idx_race_results_race ON public.race_results(race_id);

CREATE TRIGGER update_race_results_updated_at
BEFORE UPDATE ON public.race_results
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();