CREATE TABLE public.race_tier_notes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  race_id integer NOT NULL,
  tier integer NOT NULL,
  note text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (race_id, tier)
);

ALTER TABLE public.race_tier_notes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all access to race_tier_notes"
  ON public.race_tier_notes
  FOR ALL
  USING (true)
  WITH CHECK (true);

CREATE TRIGGER update_race_tier_notes_updated_at
  BEFORE UPDATE ON public.race_tier_notes
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

CREATE INDEX idx_race_tier_notes_race ON public.race_tier_notes(race_id);